apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eig2yw6ic-go
  janus-idp.io/tekton: eig2yw6ic-go
  backstage.io/kubernetes-id: eig2yw6ic-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eig2yw6ic-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
