apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eig2yw6ic-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eig2yw6ic-go 
  name: eig2yw6ic-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eig2yw6ic-go 
